foreground            #39ff14
background            #0e0e12

selection_foreground  #000000
selection_background  #d966ff

cursor                #d966ff
cursor_text_color     #000000

background_opacity    0.82
background_blur       1

color0  #111111
color1  #f7768e
color2  #39ff14
color3  #e0af68
color4  #89b4fa
color5  #d966ff
color6  #7dcfff
color7  #cdd6f4

color8  #555555
color9  #ff8ea3
color10 #5cff5c
color11 #ffd089
color12 #a6c8ff
color13 #f0a6ff
color14 #a4daff
color15 #ffffff
